name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        goos: [windows, darwin, linux]
        goarch: [amd64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Project
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o ralph-${{ matrix.goos }}-${{ matrix.goarch }} main.go
          zip ralph-${{ matrix.goos }}-${{ matrix.goarch }}.zip ralph-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ralph-${{ matrix.goos }}-${{ matrix.goarch }}.zip
          path: ./ralph-${{ matrix.goos }}-${{ matrix.goarch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v1

      - name: Create Release and Upload Artifacts
        run: |
          gh release create ${{ github.ref }} \
            artifacts/*.zip \
            --title "Release ${{ github.ref }}" \
            --notes "Release notes for ${{ github.ref }}"
        env:
          GH_TOKEN: ${{ secrets.CICD_TOKEN }}
