name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        goos: [windows, darwin, linux]
        goarch: [amd64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: latest

      - name: Build Project
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o ralph-${{ matrix.goos }}-${{ matrix.goarch }} main.go
          zip ralph-${{ matrix.goos }}-${{ matrix.goarch }}.zip ralph-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ralph-${{ matrix.goos }}-${{ matrix.goarch }}.zip
          path: ./ralph-${{ matrix.goos }}-${{ matrix.goarch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Create Release and Upload Artifacts
        uses: gh-actions/gh-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          title: Release ${{ github.ref }}
          files: |
            artifacts/*.zip
